### ISSUE TITLE
Getting 11.0 gear working in tswcalc

### ISSUE THREAD

**Issue by joakibj** [joakibj/tswcalc#33]
Investigation on how much work there is getting 11.0 gear and beyond. Plus other special drops from new raids, after Issue 12 working in tswcalc, considering the dated application design.

Current challenges: 
* Some dependency on hardcoded strings related to "10.". [example](https://github.com/joakibj/tswcalc/blob/develop/src/javascript/tswcalc-buttonbar.js#L84)
* Indices lookup on hardcoded "ql10". [example](https://github.com/joakibj/tswcalc/blob/develop/src/javascript/tswcalc-export.js#L112)
* Getting info on how to upgrade gear to 11.0 from raiders. Possible after any "world first"

Future concerns:
* New upgrade currency items from raid drops?
* Horizontal screen estate from "All 10.x" and "All 11.0" buttons at the top

**Comment by Xeio** [comment]
Created a branch to fiddle around with this and it didn't turn out to be too much work: https://github.com/Xeio/tswcalc/commits/ql11support

There's only really two things missing, a proper description and image for "Supernal Upgrade" item which currently is only known from the tooltips for the supernal upgrade kits, and actual stat values for gear at that level. Oh, and, well, some tests would be good too once we get gear values.

This will probably have to sit on hold till someone both downs a NM raid and is willing to do the work to get all the data/images. I can't just cheat it on TestLive like I could for QL10.6-10.9. ;(

**Comment by joakibj** [comment]
How is export handled with this? There were some special "ql10" handling there.

The image can be datamined easily enough from TestLive .rdbdata files once it hits there.

**Comment by Xeio** [comment]
Export/Import is mostly a matter of making 11 a special value that instead parses into "11.0" rather than "10.11".

Though I should probably take a quick look at the BBCode export too, it may already use the full QL and not need changed but I don't think I've ever used that feature. :P

**Comment by joakibj** [comment]
To be fair, I don't think anyone has used the BBcode export :cry: . Well except me the first time I pasted the thing on the forum

**Comment by Inkraja** [comment]
I also used it one time, for testing, most people share the link, and there u have everything u want.

The only cool think can be,  if u hover the link u get a stats summery as tooltip, but i think thats near impossible because u need insert a javascript snipped on the side u insert the link. And iam not sure if funcom will add it in their own forum.

**Comment by Xeio** [comment]
I found at least some of the QL 11 item IDs on Live, so actually getting that data might not be that difficult.

I have no idea how to turn the base image for a Supernal Upgrade into what actually displays in the UI though, because the SWF file is just a white overlay onto the "grid, with blue-tint background, with a purple/gold border" that's composited by the UI. Maybe there'd be some way to just mod the in-game inventory to arbitrarily fake an item being in the inventory, but I never had any luck with building add-ons.

**Comment by joakibj** [comment]
What I did with the woodcutter stuff was getting the sfw files from a tswrdb dump, using sfwtools to convert to png and set the color black to transparent.

**Comment by Xeio** [comment]
Might work as a placeholder or something, though the background for the upgrade items aren't solid. They're that blue-pattern grid (I'm assuming it's blue, to match the Astral/Crit).

Also, I'm not sure if Supernal Upgrade has a purple or gold border, I imagine that might be in the .dat file for the item, but I only spent time figuring out what the code for the image ID was.

**Comment by Inkraja** [comment]
its a purple item, so it should be a purple border
also export in 1000620 the is a small skip in the bit lengths, the name in the file has the id from a file after

**Comment by Xeio** [comment]
NY Lurker has been killed, QL11 glyph toolkit drop (11th Hour Glyph Toolkit) and the QL11 (Supernal Upgrade) are confirmed.

Talked with someone with the items about getting screen caps of the inventory we can use.

Glyphs are going to take a while, unless one of Lag Spike who loots it is willing (and has access to TL) to copy their character to TestLive a few dozen times for all the stat combinations. I might try looking into if it's possible to fake the glyphs into an item link since I found all the QL11 glyph item IDs in the dumps, but I think QL11 gear will probably be done way sooner in any case.

**Comment by Xeio** [comment]
See pull request for changes, I just faked the image composite because I'm impatient, so it doesn't have the fancy blueprint background the astral/criterion do. In related news 32x32 size really doesn't do the new Supernal Upgrade icon justice.

Other good news, I found a way to get Glyphs to work in item links, so I can probably data mine all those values.

Bad news, there's a glyph item for each slot group/stat combination, so that's like... well over 100 QL11 glyphs to data mine out. That'll be an "eventually" project.

**Comment by Inkraja** [comment]
U can do it! :D and yes it's easier to use the string ingame than using the ql think, but a better screenshot from the inventory (also for my project) will be nice :)

**Comment by Headshoty** [comment]
Hey, so I got asked to maybe upload a picture of the new supernal upgrade. well here it is: http://i.imgur.com/9PnZhYY.png

I am quite the noob for enhancing etc. It looks good this way, if I make it bigger it gets ugly as hell. :/

**Comment by Inkraja** [comment]
U have it in your inventory shotty? If yes, change the inventory ui to 200%, graphic setting on ultra and make a screenshot for the icon in the inventory. Than the icon is 89x89 px that's the highest resolution u can get.

**Comment by Headshoty** [comment]
That is... surprisingly obvious. ~.~ I totally forgot about that HUD option. Well, here goes the 200% INV-scale picture then.

http://i.imgur.com/THvySb0.png

**Comment by Inkraja** [comment]
Hmm Iam not sure, I datamined the glyphs months before, itemes with Ar/Hr/hp should also be inside itemid's but with the kit will be easier to get the infos :)

Thanks a lot for the pic! +1:

**Comment by Headshoty** [comment]
Yea as I said, I sadly can't access TL atm, otherwise I would play around with the glpyhs. :/

So, I could provide stats for Head + Majors, I sadly noticed that I don't have a .9 minor yet. :p

**Comment by Xeio** [comment]
AR/HP stats are done, just have to wait till joakibj has a chance to merge and push it live.

Thanks for the image, I'll replace the placeholder I was using with that.

**Comment by Headshoty** [comment]
Alright nice! Looking forward to it.

Good Job. :)

**Comment by joakibj** [comment]
@Xeio , any new commits to the existing PR based on stuff in this issue ?

**Comment by Xeio** [comment]
Just pushed the image, but that's the only change needed at the moment. I'm leaving Glyphs to future work.

**Comment by joakibj** [comment]
Thanks, in a future design, I think the use of icons will be dropped. It is really not that fun to maintain
