### ISSUE TITLE
Future of tswcalc. Design and tech updates in a 2.0 version

### ISSUE THREAD

**Issue by joakibj** [joakibj/tswcalc#49]
Well, serious time now. Since there are several contributors and more interest in tswcalc as an open source project, there might be time and some hands to do some proper housekeeping (and learning along the way). In an attempt to bump this to a more modern 2.0 version.

tswcalc has worked fine for over 2.5 years. Only last autumn, Funcom have pushed updates with lots of items that are not really that compatible with tswcalc architecture. Until then, NY raid items were the few proper items, rather than custom gear.

Now all the code is showing cracks, the checkbox approach is no longer viable nor maintainable. There should rather be support of being able to search for items by name and add them to the talisman slot. With the option to add signet if the item supports it (unlike NY raid items). Then allow custom gear just like now, but rather than forcing to choose a role on the talisman like now, they add the custom item base name and then customize the glyphs and signet in a similar fashion.

A few months ago there was a player named Hark that contacted me on email and proposed this design for future tswcalc versions: https://docs.google.com/spreadsheets/d/12RVB8Y4swDvezEWHRR1CuP61enIAO67evdGYNUhag5Y/edit?usp=sharing

I think something similar would be neat to have. Cut out the icons, keep it tight and add support for searching items and signets by name.

Now to my second point on this agenda. I'd like to see tswcalc get more up to date with modern JavaScript standards. Migrating from grunt to gulp, pure jquery to angularjs or react and update bootstrap and the design.

Third, manually noting down items is cumbersome. Players should be able to stay ahead of the curve and get the data out of TestLive in an automated fashion. It would be fun to revive some work in https://github.com/joakibj/tswrdb . I KNOW the full items are in there somewhere and they should be able to be extracted as json/xml fully and automatically.

Lastly, my personal motivation for this, since I don't actually play the game any longer is to keep up to date with technology as a professional. I have my own private little consultancy firm that I sink my time in to now. This is also the reason while PR takes a little time to get merged :stuck_out_tongue_closed_eyes:

**Comment by Xeio** [comment]
>A few months ago there was a player named Hark that contacted me on email and proposed this design for future tswcalc versions

Just to note, this doc is private. :P

>I KNOW the full items are in there somewhere and they should be able to be extracted as json/xml fully and automatically.

I was fiddling around with it the other day... the .dat binary format is kind of a nightmare though. It seems like there's multiple formats depending on what the item actually is, and some of them have seemingly redundant data points (HR/AR Custom Nightwatch Head piece as an example, but NOT the HP Custom Nightwatch Head piece, no idea why). Like even the "string name" seems to have a different control code depending on how old the item data is... those just happen to be easy to find because they're all ASCII.

**Comment by joakibj** [comment]
> Just to note, this doc is private. :P

Copied to my own Drive and shared:
https://docs.google.com/spreadsheets/d/12RVB8Y4swDvezEWHRR1CuP61enIAO67evdGYNUhag5Y/edit#gid=0

**Comment by Xeio** [comment]
That looks nice. Admittedly I'm better at the back ends, I have naught the flair for style and visual design and most of the work I do for a living is in Win Forms.

**Comment by joakibj** [comment]
Yeah I agree, more intuitive since it mimics the layout of the in-game talisman character inventory as well. I work a lot of backend too, so have to make this stuff to stay updated.

Another fun thought would be to make tswcalc a more complete, by adding ability builds, augment and AEGIS support.

**Comment by Xeio** [comment]
If it makes you feel better about not having a lot of time to maintain TSWCalc though, I've had a pull request that fixes a critical bug in grunt-lib-phantomjs since last July now. I can't even run the TSWCalc unit tests on windows without having it applied locally.

So, I mean, a day or two of turnaround isn't bad all things considered. <_<

**Comment by joakibj** [comment]
Really? I don't have any locally applied fixes on Win7. Do you have the exact versions of grunt, npm, node.js as in the README?

**Comment by Inkraja** [comment]
dont make work on the new nm items, i will send u in an email

desgin: ofc i only can do suggestion because its your baby, but i like the design, but a mix from the suggestion from hark and your design will be a nice , so keep your design but sort they like ingame (head on top, next 3 the 3 majors and so on)

Adding ability and augments:
in my eyes both not important for gear, because u need to bind them on a activ ability and they can be quite different

**Comment by Xeio** [comment]
>Really? I don't have any locally applied fixes on Win7. Do you have the exact versions of grunt, npm, node.js as in the README?

As far as I'm aware, yes. [It's related to the way grunt-lib-phantomjs cleans the temp files](https://github.com/gruntjs/grunt-lib-phantomjs/pull/85/files), in particular before the process using the file has necessarily terminated.

It's sort of a non-deterministic error. I can build maybe 1 in 20 times successfully without the patch, usually just one or two tests fail per pass.

>Adding ability and augments:
in my eyes both not important for gear, because u need to bind them on a activ ability and they can be quite different

Yea, there's still TSWBuilder hanging around too, though I don't know if anyone has kept that recently updated. I think it'd be better to keep builds separate from gear in general. The only real oddity is the HP/AR/HR augments since they can affect the character sheet.

AEGIS is certainly an interesting possibility to add, though that could almost use a dedicated page rather than being tacked onto TSWCalc. Especially since Funcom has vaguely said they to intend to take endgame in the direction of new AEGIS in future zones.

**Comment by Inkraja** [comment]
other hand on aegis u didnt switch a lot, if u heal u max the healer think, as dps the dps thing, so u  try to be max, there are no 1*heal 2*dps and 1tank

**Comment by joakibj** [comment]
Yeah it was just a thought, anyways, there is gonna be some changes over time. Both to tech and design as time permits.

**Comment by joakibj** [comment]
Closing issues since Secret World Legends has a different gear system and is likely to replace TSW over time.
